---
namespace: middleware_automation
name: eap_cluster_kubevirt
version: "1.0.0"
readme: README.md
authors:
  - Guido Grazioli <ggraziol@redhat.com>
description: Validated content candidate
license_file: "LICENSE"
tags:
  - wildfly
  - eap
  - jboss
  - server
  - infrastructure
  - runtimes
  - middleware
  - a4mw
dependencies:
  "middleware_automation.wildfly": ">=1.3.4"
  "kubevirt.core": ">=1.0.0"
  "ansible.posix": ">=1.4.0"
repository: https://github.com/ansible-middleware/eap-cluster-ocpv
documentation: https://ansible-middleware.github.io/eap-cluster-ocpv
homepage: https://github.com/ansible-middleware/eap-cluster-ocpv
issues: https://github.com/ansible-middleware/eap-cluster-ocpv/issues
build_ignore:
  - .gitignore
  - .github
  - .ansible-lint
  - .yamllint
  - '*.tar.gz'
  - '*.zip'
  - molecule
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
