plugin: kubevirt.core.kubevirt
connections:
  - host: https://kubernetes.default.svc
#    api_key: "{{ lookup('ENV', 'K8S_AUTH_API_KEY') }}"
    validate_certs: false
    namespaces:
      - kubevirt
