---
- name: Playbook for installing prerequisites
  hosts: all
  tasks:
    - name: "Manage subscription"
      redhat.rhel_system_roles.redhat_subscription:
        state: present
        username: "{{ sub_username }}"
        password: "{{ sub_password }}"
        auto_attach: true
      become: yes
    - name: "Install packages"
      ansible.builtin.include_role:
        name: fastpackages
      vars:
        packages_list:
          - procps-ng
          - mailcap
          - unzip
          - firewalld
          - ca-certificates
          - python3-lxml
          - net-tools
          - python3-policycoreutils
          - policycoreutils-python-utils
          - "{{ jvm_package }}"
    - name: "Get FQDN"
      ansible.builtin.command: "setenforce Permissive"
      become: yes
      changed_when: false
    - name: "Get FQDN"
      ansible.builtin.command: "hostname --fqdn"
      become: yes
      register: current_fqdn
      changed_when: false
    - name: "Set FQDN"
      ansible.builtin.command: "hostnamectl set-hostname --static {{ inventory_hostname }}{{ domain_name }}"
      become: yes
      when: current_fqdn.stdout != (inventory_hostname + domain_name)
    - name: "Install certificates"
      ansible.builtin.include_role:
        name: certificates
