---
- name: Playbook for Wildfly Hosts
  hosts: label_app_wildfly
  become: yes
  roles:
    - middleware_automation.wildfly.wildfly_install
    - middleware_automation.wildfly.wildfly_systemd
  pre_tasks:
    - name: Create cluster node list
      ansible.builtin.set_fact:
        eap_cluster_nodes: >
          {{ eap_cluster_nodes | default([]) + [
               {
                 "name": item,
                 "address": 'jgroups-' + item,
                 "inventory_host": hostvars[item].ansible_default_ipv4.address | default(item) + '[7600]',
                 "value": hostvars[item].ansible_default_ipv4.address | default(item)
               }
             ] }}
      loop: "{{ ansible_play_batch }}"

- name: Playbook for Wildfly Hosts config and app deployment
  hosts: label_app_wildfly
  become: yes
  serial: 1
  tasks:
    - name: Verify service is started
      ansible.builtin.service:
        name: eap
        state: started
      throttle: 1
    - name: Verify management port is accessible
      ansible.builtin.wait_for:
        port: 9990
        host: localhost
        connect_timeout: 3
        delay: 10
        timeout: 60
    - name: "Download demo app to deploy from {{ app_url }} into deployments"
      ansible.builtin.get_url:
        url: "{{ app_url }}"
        dest: "{{ wildfly_home }}/standalone/deployments/"
        owner: eap
        group: eap
        mode: 0644
