---
wildfly_config_base: standalone-ha.xml
wildfly_offline_install: False
wildfly_enable_yml_config: True
wildfly_statistics_enabled: True
wildfly_apply_cp: True
wildfly_systemd_enable: True
wildfly_bind_addr_private: "{{ ansible_default_ipv4.address }}"
wildfly_bind_addr_management: 0.0.0.0
wildfly_instance_name: "{{ inventory_hostname }}"
wildfly_elytron_adapter: False
wildfly_yml_configs: [ wildfly_ymlconfig.yml.j2 ]
wildfly_app_firewalld_enabled: True
wildfly_listen_ports:
  - 8009/tcp
  - 8080/tcp
  - 9990/tcp
  - 7600/tcp
  - 7601/tcp

jdbc_driver_module_dir: "{{ eap.home }}/modules/org/mariadb/main"
jdbc_driver_version: 2.7.4
jdbc_driver_jar_filename: "mariadb-java-client-{{ jdbc_driver_version }}.jar"
jdbc_driver_jar_url: "https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/{{ jdbc_driver_version }}/mariadb-java-client-{{ jdbc_driver_version }}.jar"
jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
jdbc_driver_module_name: "org.mariadb"

app_url: https://github.com/ansible-middleware/addressbook/releases/download/1.0.7/addressbook.war
addressbook_jdbc_url: "{{ site_jdbc_url }}/addressbook"
